### ISSUE TITLE
Ctrl-C from `test.bash` leaves zombie processes

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#141]
The `test.bash` script starts up the necessary servers when it is run.  They are started in a process group and the script terminates them when it completes.  However, if the script is terminated using `Ctrl-C` then the part that terminates the servers does not run.  The effect is that there can be a bunch of zombie servers running. This creates stability issues with Cypress and also bogs down the dev environment.

I'm not sure what the solution is here... maybe its possible to tie this process group to the process running `test.bash` so that when it exits they are also terminated?

**Comment by WarpWing** [comment]
> The `test.bash` script starts up the necessary servers when it is run. They are started in a process group and the script terminates them when it completes. However, if the script is terminated using `Ctrl-C` then the part that terminates the servers does not run. The effect is that there can be a bunch of zombie servers running. This creates stability issues with Cypress and also bogs down the dev environment.
> 
> I'm not sure what the solution is here... maybe its possible to tie this process group to the process running `test.bash` so that when it exits they are also terminated?

Just saw this and looked over the code. I think it's just that the cleanup part of `test.bash` isn't called if the script is prematurely interrupted. From what it looks like, implementing a cleanup function and creating a bash trap to catch `SIGINT`s would possibly solve the problem. Would like your thoughts before proceeding.

Something like this:

```bash
# Example for FD2 DEV GID
cleanup() {
  echo "Cleaning up..."
  if [ -n "$DEV_GID" ]; then
    echo "Terminating the dev server..."
    kill -INT -- -"$DEV_GID"
    echo "Dev server terminated."
  fi
  # Checks for Preview, Live, and Builder etc
  exit 0
}

# Trap SIGINT (Ctrl-C) and SIGTERM
trap cleanup SIGINT SIGTERM

# Call Cleanup on normal use
cleanup
```

**Comment by braughtg** [comment]
This sounds like a viable approach.  You'll just need to test it to be sure it does what is needed.  The way to test is to run something like:
- Do a `ps -ax` to see what processes are running.  
- Run `test.bash --e2e --fd2 --dev --gui` in a terminal in the Linux Dev Environment.  
- When the Cypress window is up, do another `ps -ax` and you'll see the server processes that were started.
- `Ctrl-C` the terminal 
- Check `ps -ax` again to ensure that the server processes are gone.

Feel free to make a PR if everything checks out.

Thanks!

**Comment by WarpWing** [comment]
> This sounds like a viable approach. You'll just need to test it to be sure it does what is needed. The way to test is to run something like:
> 
>     * Do a `ps -ax` to see what processes are running.
> 
>     * Run `test.bash --e2e --fd2 --dev --gui` in a terminal in the Linux Dev Environment.
> 
>     * When the Cypress window is up, do another `ps -ax` and you'll see the server processes that were started.
> 
>     * `Ctrl-C` the terminal
> 
>     * Check `ps -ax` again to ensure that the server processes are gone.
> 
> 
> Feel free to make a PR if everything checks out.
> 
> Thanks!

Changes check out on my end. PR: #144
