### ISSUE TITLE
Return to FD2 form after using + button

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#152]
Many of the FarmData2 components include `+` buttons to add new farmOS content (e.g. crops, locations, tray sizes, equipment, etc).  When a `+` button is clicked the user is directed to a farmOS form that allows them to create the relevant content.  Currently when the "Save" button is clicked on those forms the user is redirected back to an empty version of the form.  It would be better to have the user redirected back to the FarmData2 form where the `+` was clicked and also to ensure that any form content is retained. 

In addition, if it is possible, the newly created content (e.g. crop, location, etc.) should be selected in the appropriate field under the assumption that it was created so that it could be used.

Related to #103 which will need to be addressed first.

**Comment by braughtg** [comment]
In addressing this issue the component showing the `+` button should be able to obtain the current URL and use that to determine the page to return to, rather than having the entry point pass the URL as a prop.  This is necessary because components are used on multiple different pages.

With the URL to which to return known, it can simply be appended to the end of the URL of the farmOS form using the `?destination=...` query parameter.  For example, the `+` button in the `CropSelector` currently links to:

`/admin/structure/taxonomy/manage/plant_type/add`

If that URL were set to:

'/admin/structure/taxonomy/manage/plant_type/add?destination=/fd2/main'

then the user would be taken to the main FD2 page when the form is submitted.

It is this last part of the URL (`/fd2/main`) that the component will need to replace with the relevant part of the URL for the page that is currently displaying the component.

**Comment by braughtg** [comment]
Testing this functionality will be a little tricky... whatever is used to get the current page may or may not work when running component tests.  It should work because component tests are run in the browser, but the URL will be different than it will be when running a page in the dev or live farmOS server.  So, it may be the case that this functionality can only be partially tested in the component tests and then page specific tests will need to be added to the e2e tests for the page.

**Comment by JingyuMarcelLee** [comment]
I checked this and thought maybe we could have the ```+```  open a new tab or small browser window that shows the form for adding content. Once the user makes the change, the dropdown should be updated by listening to changes made in the DB and refresh the page or listen to the changes made to the Map binded to the Vue dropdown component which should be sent from the server side and reload the dropdown component. 

Displaying the form on a new tab would be an easy fix with just ```target="_blank"``` next to ```href``` in ```CropSelector```. This would also retain the user input. However, this wouldn't update the dropdown as mentioned in  #103. I will take a look at this issue later this week.

**Comment by JingyuMarcelLee** [comment]
Also, let me know if you think we should go with the option that you mentioned in the issue description. I could be wrong, if we want to have the user come back to the seeding form with their input retained after adding new terms with a ```+``` on the same browser tab, this would require some kind of state management (maybe with pinia) or caching the user input. I'm not sure if this would be the best choice.

**Comment by braughtg** [comment]
> I checked this and thought maybe we could have the `+` open a new tab or small browser window that shows the form for adding content. 

I would prefer not to open a new tab or window for this.  Two options that I like are:
- We can use the `?destination` part of the URL to return back to the correct page, which should be pretty easy and is probably the way to implement it to start.
- We could possibly use a [Bootstrap Vue Overlay](https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/overlay.html) with custom content being the farmOS page for creating the new term or asset.  I think this would be harder and I'm not 100% sure it is viable solution.

> Once the user makes the change, the dropdown should be updated

To make this happen, I think all that is needed is to clear the cached contents of the appropriate type of information (e.g. crops, fields, etc.). There are functions in the `farmosUtil` library for clearing the cached contents.  Then when the page is reloaded it will automatically fetch the new contents.  There may be more performant ways to do it by updating the information locally, but I don't think we need to do that unless we see a detrimental performance impact.

>  if we want to have the user come back to the seeding form with their input retained after adding new terms with a + on the same browser tab, this would require some kind of state management (maybe with pinia) or caching the user input

We definitely want any fields that the user filled in before clicking `+` to still be filled in when they return to the form.  As you suggest this means the handler for the `+` button will need to cache the contents before leaving the page, and then restore them upon return.  A JavaScript global is probably sufficient for this as it is transient.  But currently, Pinia is installed and imported into the pages - though it is not currently used and I was thinking about removing it.  Though, if you think it is the right solution here, please discuss why in a comment.

**Comment by JingyuMarcelLee** [comment]
> To make this happen, I think all that is needed is to clear the cached contents of the appropriate type of information (e.g. crops, fields, etc.). There are functions in the `farmosUtil` library for clearing the cached contents. Then when the page is reloaded it will automatically fetch the new contents. There may be more performant ways to do it by updating the information locally, but I don't think we need to do that unless we see a detrimental performance impact.
> 
> >

This sounds fine for fetching the dropdown update. Does this mean when the user completes the form for adding a new term, it should also call the function clearing the cache so that the dropdown can refetch the updated crops list? Or should we always clear the cache when the input form loads?  

> We definitely want any fields that the user filled in before clicking + to still be filled in when they return to the form. As you suggest this means the handler for the + button will need to cache the contents before leaving the page, and then restore them upon return. A JavaScript global is probably sufficient for this as it is transient. But currently, Pinia is installed and imported into the pages - though it is not currently used and I was thinking about removing it. Though, if you think it is the right solution here, please discuss why in a comment.
> 
> >
As you suggested, I think a JavaScript global should be sufficient in this form. The only case in which I would use Pinia is when there are shared states or data that need to be reused by multiple vue components or pages. Pinia has nice global storage where we can save component states that can be hot-module-replaced. I was thinking of using it in the case where we have a new tab or browser to add a new term, then hot-replace the component state in the original form with the updated term. I don't think this would be necessary if we are returning to the form after adding a new term.
