### ISSUE TITLE
Chromium-based browser fails to run FarmOS on localhost 

### ISSUE THREAD

**Issue by JingyuMarcelLee** [FarmData2/FarmData2#163]
Any Chromium-based browser (Google Chrome, Microsoft Edge) fails to run FarmOS on localhost. It displays the default Apache2 Server page instead of the FarmOS login page once I navigate to ```http://localhost:80```. This happens only in Chromium-based browsers. Everything works fine with Firefox. 

When I use Chromium-based browser to visit ```localhost:80``` :

![image](https://github.com/FarmData2/FarmData2/assets/46755208/b2de9212-2e2e-4f50-8cb8-cce31145e50e)

The docker log for  ```FarmOS``` container when I use Chromium-based browser catches ```SIGWINCH``` which is ```SIGNAL WINDOWS CHANGE``` : 

![image](https://github.com/FarmData2/FarmData2/assets/46755208/383a0147-4581-4d27-a1c9-47b2badd6023)

When I use Firefox to  visit ```localhost:80```:

![image](https://github.com/FarmData2/FarmData2/assets/46755208/3cb23b5d-85ee-45b0-8244-f13762a5bca1)

The docker log also correctly displays the ```GET``` request:

![image](https://github.com/FarmData2/FarmData2/assets/46755208/3fbb9ba4-843a-4e47-9cd5-067b26300340)

To replicate this, follow ```INSTALL.md``` and visit ```localhost:80``` on your Chromium-based browser on your host machine, not inside the dev container using vnc.

**Comment by WarpWing** [comment]
> Any Chromium-based browser (Google Chrome, Microsoft Edge) fails to run FarmOS on localhost. It displays the default Apache2 Server page instead of the FarmOS login page once I navigate to `http://localhost:80`. This happens only in Chromium-based browsers. Everything works fine with Firefox.
> 
> When I use Chromium-based browser to visit `localhost:80` :
> 
> ![image](https://private-user-images.githubusercontent.com/46755208/305266065-b2de9212-2e2e-4f50-8cb8-cce31145e50e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDcwNjgsIm5iZiI6MTcwODEwNjc2OCwicGF0aCI6Ii80Njc1NTIwOC8zMDUyNjYwNjUtYjJkZTkyMTItMmUyZS00ZjUwLThjYjgtY2NlMzExNDVlNTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMTE0NDFhOTdjMWQyZGE2YWRjMjEyYTBjMjg2ZTdhMGRjNjQ0MzE3YmI5ODk2MDZjZDA1OThjZjlkOTMxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YQP-yp4XKo8cVNpNm10Bjw3gNKnxufRoC7JWl23UYpE)
> 
> The docker log for `FarmOS` container when I use Chromium-based browser catches `SIGWINCH` which is `SIGNAL WINDOWS CHANGE` :
> 
> ![image](https://private-user-images.githubusercontent.com/46755208/305266653-383a0147-4581-4d27-a1c9-47b2badd6023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDcwNjgsIm5iZiI6MTcwODEwNjc2OCwicGF0aCI6Ii80Njc1NTIwOC8zMDUyNjY2NTMtMzgzYTAxNDctNDU4MS00ZDI3LWExYzktNDdiMmJhZGQ2MDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOWJlNGUxODgxZWY0ZDhiMTk5MTNhZDVmM2FkODJjNjM5OGJjYTQ3YTVlNGU5YjhlZDdjMzVkODU3MTg2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDtKshWjbvWInhSensR2t180NW5518-dbozONYsf-1A)
> 
> When I use Firefox to visit `localhost:80`:
> 
> ![image](https://private-user-images.githubusercontent.com/46755208/305266242-3cb23b5d-85ee-45b0-8244-f13762a5bca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDcwNjgsIm5iZiI6MTcwODEwNjc2OCwicGF0aCI6Ii80Njc1NTIwOC8zMDUyNjYyNDItM2NiMjNiNWQtODVlZS00NWIwLTgyNDQtZjEzNzYyYTViY2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMjM3NzRlMzBhMTVlZGEwNzBiMzRhZDg5ZDJmNjNmYzE2YTcwZjc4MzU1NjFlNzFjNmJlZGY5MjZkNTczZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNmH-fLE7oN1Lm4oDBgvnakk8vsXOg7a41G30VlG25s)
> 
> The docker log also correctly displays the `GET` request:
> 
> ![image](https://private-user-images.githubusercontent.com/46755208/305266822-3fbb9ba4-843a-4e47-9cd5-067b26300340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDcwNjgsIm5iZiI6MTcwODEwNjc2OCwicGF0aCI6Ii80Njc1NTIwOC8zMDUyNjY4MjItM2ZiYjliYTQtODQzYS00ZTQ3LTljZDUtMDY3YjI2MzAwMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDE4MDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNzA4NjZlY2QxMWQ2OWNhZDRkMTkzZjRlODQxZTU2MmRmZDY2MzIxNzJmMGQ1NTNhNjRkNDc0NzI0MjYxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cqJMPJUWK2FHllTtEvxXxE6l-i8T8o3qtpx0wmK10QA)
> 
> To replicate this, follow `INSTALL.md` and visit `localhost:80` on your Chromium-based browser on your host machine, not inside the dev container using vnc.

That's strange, my first thought is that it could be a networking profile or browser caching issue. Is it possible that Apache's vhost config has something weird with chromium browsers? I'll look into it when I get back from classes.

**Comment by braughtg** [comment]
At present, the farmOS server is designed to be run and accessed within the FarmData2 dev environment.  So not too surprising that there is an issue with this, as it hadn't been tested.  That said, it would be great if this could be made to work.  One thought is that this issue may be obsoleted by #77.

**Comment by braughtg** [comment]
#77 has been merged.  A Zulip stream has been opened for community support for native installs which are not currently supported by the main project.  A link to this issue has been placed there https://farmdata2.zulipchat.com/#narrow/stream/434384-developer-native-install
