### ISSUE TITLE
PickerBase: Add a context sensitive icon to "All" button 

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#166]
__Current Behavior__

Currently the `PickerBase` component displays an "All" button. This button can be seen in the `BedPicker` on the Direct Seeding form (which is created using a `PickerBase` component)  by selecting a Location that has beds (e.g. `CHUAU`).

![image](https://github.com/FarmData2/FarmData2/assets/16962482/edf3d6aa-fec7-45b6-a1ff-7dc066fb2307)

Clicking the "All" button either selects all of the beds (if they are not all selected) or deselects all beds (if they are all selected).  

__Desired Behavior__

The `PickerBase` class should have a button that displays something context sensitive that indicates what will happen if it is clicked.  Maybe we could use an icon like:  
:white_check_mark: All (when it will select all)
or
:no_entry_sign: All (when it will clear all)

Other proposals for the design of the buttons should be proposed here for discussion before implementation.

**Comment by braughtg** [comment]
@WarpWing I made some edits to the issue description above.  This change should be made in the `PickerBase` component not in the `BedPicker` component.  The `BedPicker` is created using a `PickerBase` so putting this functionality into the `PickerBase` will also add it to the `BedPicker` as well as any other components that are made from `PickerBase`.

**Comment by WarpWing** [comment]
> @WarpWing I made some edits to the issue description above. This change should be made in the `PickerBase` component not in the `BedPicker` component. The `BedPicker` is created using a `PickerBase` so putting this functionality into the `PickerBase` will also add it to the `BedPicker` as well as any other components that are made from `PickerBase`.

I'll revert my BedPicker changes and then finalize the PickerBase logic and run tests.
