### ISSUE TITLE
Component Examples: Build a `farm_fd2_examples` example for each component. 

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#169]
For each component in `components` build a simple example entry point in `farm_fd2_examples` that illustrates its use.  The example should:
- Give a short description
- Display the component offset by `<hr>` elements.
- Provide a `<tablle>` of controls that allow the user to modify each of the component's props, including:
    - Make the component required or not
    - Show or hide the validity styling
    - Change value(s) collected by the component
- Display a `<table>` of the events and payloads from the component, including:
  - The component's required state
  - The component's validity
  - The value(s) emitted as `update` events by the component.

In addition:
- The example should be listed and linked on the Component Examples page
  - In`App.vue` in the `component_examples` entry point.
- The component's jsdoc comments should include:
  - a link to the live example
  - a link to the example source code
  - the code used to place the component in the example template as the static example.

Use the completed examples listed below as a guide for new examples.

Full details of the process for creating an example are given in [this comment below](https://github.com/FarmData2/FarmData2/issues/169#issuecomment-1973501278).

Examples needed for:
- [x] #175
- [x] #344
- [x] #348
- [x] #171
- [x] #349
- [x] #360
- [x] #355
- [x] #177
- [x] #187
- [x] #184
- [x] - #262
- [x] #356
- [x] #358

To work on one of these, request to be assigned one of the components in the comments below.  A maintainer will create an issue for that specific component for you to work on.

**Comment by braughtg** [comment]
How to build an example:

- Use the `addEntryPoint.bash` script to create the new example
  - Use the following as a guide for answering the prompts from the script:
    - Add the entry point in the `farm_fd2_examples` module
    - Name: `component_name` (e.g. `bed_picker`)
    - Title: `ComponentName Example` (e.g. `BedPicker Example`)
    - Description: "Example of the use of the ComponentName component."
    - Permissions: `access content`
  -  The script will create and switch you to a new feature branch for the example.
 
- In the new feature branch branch created: 
  - Commit the initial version of the example as generated by the `addEntryPoint.bash` script.
  - In the `farm_fd2_examples/module` directory
    - Edit the `farm_fd2_examples.links.menu.yml` file
      - Remove "Example" from the title to match others.
  - In the `farm_fd2_examples/component_name` directory (e.g. `bed_picker`, etc)
    - Delete the following files
       - `lib.js`
       - `lib.sample.unit.cy.js`
    - Edit the `App.vue` file to produce the example.
       - Use the other examples (e.g. `date_selector/App.vue`, `bed_picker/App.vue`) as a guide.
  - Edit the `App.vue` file in `component_examples`.
    - add a link to the new example and brief description.
    - keep examples in alphabetical order.
  - In the `components/ComponentName/App.vue` file (e.g. `components/PickerBase/App.vue`)
    - Add links to the "Live Example" and it "Source".
    - Add a "Usage Example" by copying the component's element from the example's `<template>`
    - See `BedPicker/App.vue` for an example.

- Push your feature branch.
- Make a PR with a "Closes #" tag for the component specific issue that was created for you.
- Request a review from the maintainer that created the issue when your example is complete.

**Comment by sidlamsal** [comment]
I would like to be assigned the CommentBox example page.

**Comment by sidlamsal** [comment]
I would like to be assigned the CropSelector example page.

**Comment by sidlamsal** [comment]
I would like to be assigned the EquipmentSelector example page.

**Comment by sidlamsal** [comment]
I would like to be assigned the NumericInput example page.

**Comment by sidlamsal** [comment]
I would like to be assigned the SubmitResetButtons example page.

**Comment by sidlamsal** [comment]
I would like to be assigned the TextDisplay example page.

**Comment by sidlamsal** [comment]
I would like to be assigned the LocationSelector example page.
