### ISSUE TITLE
NumericInput: Round to nearest increment when using increment buttons

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#204]
The value in a `NumericInput` is equal to the smallest increment then when the medium or large increments are clicked the value in the field should be rounded down to the value of that increment.  

Examples (assuming the smallest increment is 1):
- If the value in the field is 1 and the large increment is 100, if the large increment button is clicked, the value in the field should become 100, not 101.
- If the value in the field is 1 and the medium increment is 10, if the medium increment button is clicked, the value in the field should become 10, not 11.

**Comment by RolandLocke** [comment]
The solution to this issue should be both instantly understandable and applicable to all default value cases. This chart was drafted in attempt to cover all the cases:
![Image](https://github.com/user-attachments/assets/5906b7da-760d-4e29-8ec9-587590ffb034)

**Note**: The Issue in not solved by this chart. A scenario where the default value is larger than 1 and the user wanted to increment by more than 1, the value  would be overwritten by the new user input. 

Example:

1. default form value is 60
2. user increments value by 10
3. According to this chart, the value will become 10. Not 70 as would be expected.

The solution to this issue should be both instantly understandable and applicable to all default value cases. It is understood that the grayed out buttons are good for user comprehension as well as the input box clearing when the default value is currently in the box. These features should be included in the pull.

**Comment by braughtg** [comment]
> The Issue in not solved by this chart. A scenario where the default value is larger than 1 and the user wanted to increment by more than 1, the value would be overwritten by the new user input.

Here is a rule that I think works:
```
If the component is in its default state (i.e. has not been manually edited and no increment or decrement buttons have been clicked):
  If an increment button larger than the current value is clicked (e.g. value 60, click +100)
    The value is set to the next higher value of that increment (e.g. value -> 100).
  otherwise (e.g. value 60, click +10)
    The value is incremented based on the button that is clicked. (e.g. value -> 70)
otherwise
  The value is incremented or decremented based on the button clicked (respecting the disabling of buttons as described above).
```

Thoughts?

**Comment by RolandLocke** [comment]
Right now I'm coming up with the logic to determine what buttons are disabled. 

Here is what I have:![Image](https://github.com/user-attachments/assets/669eba30-41a4-461b-91d1-6b613705ef97)

The logic happens in the DisabledSmallDec, DisabledMediumDec, DisabledLargeDec. Where the return value is v-bound to the "varient" attribute of the button. 

My intuition tells me a computed property is not the right place to put this logic. But I'm not sure where to turn to for a better option. Maybe a better option is: A method that is called by the watch property using the $emit feature?

Still wrapping my head around the Vue stuff. Please let me know.

**I should note the logic here works. I just need to know if there is a more straight forward way that I'm not seeing due to unfamiliarity with Vue.

**Comment by braughtg** [comment]
> My intuition tells me a computed property is not the right place to put this logic.

Turns out your initial intuition to use computed properties here was right.  This is exactly the type of thing that computed properties are for.

That said, I think that instead of (or maybe in addition to) changing the variant you'll need to set the `disabled` attribute of the button as well.

One other thing to consider here is that the component has a minimum value (set by the `minValue` prop and that value may not be 0.  So the logic for these computed properties will need to be a little more complex to consider the minimum value.

**Comment by RolandLocke** [comment]
This ternary operator changes the style when `DisableLargeIncDec` is changed, but not to the "success" style. Instead the button has no styling at all. Do I have the quotes wrong? No quite sure what's happening.

![Image](https://github.com/user-attachments/assets/b1564dfe-fcc1-4ba6-b936-ca570eb2485e)

**Comment by braughtg** [comment]
> Instead the button has no styling at all. Do I have the quotes wrong? No quite sure what's happening.

You need to `v-bind` the `variant` attribute because it is no longer a constant and must be evaluated by Vue.

so you want `v-bind:variant="disableLargeIncDec...`

A few additional comments:
- Try to use `v-bind`, `v-model`, and `v-on` instead of their shortcut notations.  This will keep the syntax consistent across all of FarmData2 and I think its easier for newcomers to read without having to remember the shortcuts.
- I think you'll want separate computed properties for `disableLargeInc` and `disableLargeDec` because the conditions will be different.  So you'll want to change the name of the computed property `disableLargeIncDec`.

**Comment by braughtg** [comment]
One additional consideration here... should the decrement buttons behave similarly to the increment buttons when they are initially clicked?  That is, if for example the value is 150 and a decrement 100 button is clicked should it go down to 100 or down to 50?  This seems to me less intuitive than the increment case.  Thoughts?
