### ISSUE TITLE
`setup.bash` should build the docs

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#261]
Add to the `setup.bash` script a step that builds the documentation of the Components and Libraries.

This should run `npm run docs:gen` or the `makeDocs.bash` script directly.

**Comment by Shahir-47** [comment]
Hi Professor Braught,

I believe I fixed the issue and tested it as well. I have attached the changes I made to the setup.bash below:

![image](https://github.com/FarmData2/FarmData2/assets/98346408/a5482b7f-1f1c-45ba-9e02-c3ce29baa5a8)

However, when I try to stage and commit this I get the following error:

![image](https://github.com/FarmData2/FarmData2/assets/98346408/69e98163-3fa5-4653-958a-a7fca495f4bd)

**Comment by braughtg** [comment]
The fix for building the docs looks good.  

I'll move this to the project board.  As you have some time here and there see if you can dig into why the `shfmt` command is giving this error and why we aren't seeing the same linting feedback in VSCode.  Maybe we can figure out how to get the two in sync.

**Comment by braughtg** [comment]
This appears to be related to the `envman` program.  There is a line at the end of the `.bashrc` file when things are working:
```
# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
```

This line is missing from installs where the `shfmt` command does not work.  The line in question effectively adds the `~/.local/bin` directory to the `PATH` which is where the `shfmt` command is installed.

The open question is how did the above line get into the `.bashrc` in some cases and not in others?

**Comment by braughtg** [comment]
> The open question is how did the above line get into the `.bashrc` in some cases and not in others?

The line in question seems to be being added by `webi` the web installer.  So perhaps I had installed that manually at some point and that config was stored in my `fd2dev` docker volume. ???

One possible solution is to add: `/home/fd2dev/.local/bin` to the path in the Dockerfile for building `fd2dev` image in `https://github.com/FarmData2/FD2-Images`.

**Comment by braughtg** [comment]
More information:  The line in question does appear at the end of the `.profile` just not at the end of `.bashrc`.
