### ISSUE TITLE
NumericInput Component: Increment on empty field bug

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#326]
## Observed Behavior

If a `NumericInput` component has an empty value (`''`) the first click on any of the increment buttons sets its value to the minimum value for the component. 

- Go to Tray Seeding
- Click in and clear the "Trays" field.
- Click on any of the increment buttons.
- Observe the value as 0.01.
 
## Desired Behavior

If the field is blank its value should become the value of the increment if it is valid, and remain blank if it is not.  For example, clicking on a large increment with value 10, should set the field's value to `10` not to the minimum value. 

If the field is blank and a decrement button is clicked the behavior is less clear:
- Should it set the value to the minimum?
- Should it leave the value blank?
- This should be discussed here before implementation.

The behavior when the field is not blank should not be changed.

**Comment by braughtg** [comment]
Note that #204 addresses the lack of clarity of what to do when the decrement button is clicked on an empty field by indicating that the decrement buttons will be disabled when the field is empty.

**Comment by RolandLocke** [comment]
Generally, I believe the behavior should be:

If the user has cleared the current field, then the increment amount they click should be what populates the field.

Theory being the user has cleared the field to write in a new value.
