### ISSUE TITLE
Change LocationSelector "+" button URL

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#376]
Clicking the "+" button in the `LocationSelector` on the Direct Seeding, Cover Crop Seeding, Transplanting and Soil Disturbance pages currently displays farmOS's general asset creation page, allowing any type of asset to be created.  This behavior is part of the `LocationSelector` component and is controlled by the props that set the types of locations that are to be included in the drop down list.   

The `LocationSelector` component should be adjusted so that:
- If **only** greenhouses are included in the drop down, then the farmOS form for creating structure assets should be shown.
- Otherwise the farmOS form for creating land assets should be shown.

The e2e tests associated with the `LocationSelector` that check the URLs will then also need to be updated.

Note that there is a use case where the user may want to create a new greenhouse with beds inside of it.  For this use case the structure asset will have to be created separately using farmOS directly.  Once that asset is created then the "+" on the `LocationSelector` will allow the user to create a new bed with the structure as a parent.  This is an uncommon use case because the construction of new greenhouses is presumably a rare occurrence.

**Comment by braughtg** [comment]
It would be good to also clarify the documentation for the `includeGreenhouses` and `includeGreenhousesWithBeds` props to be more clear about exactly how they operate.

**Comment by Shahir-47** [comment]
After discussing with @braughtg, we've decided to adjust the LocationSelector component behavior. If fields are included in the dropdown, the '+' button should direct to the farmOS form for creating land assets. Otherwise, it should lead to the form for creating structure assets.

**Comment by Shahir-47** [comment]
Hi @braughtg,

I noticed `includeGreenhousesWithBeds` is enabled for Direct Seeding, even though direct seeding usually applies to open fields. Is there a reason for including beds here, or should it just focus on fields? Would love some context on this setup—thanks!
