### ISSUE TITLE
Update to `docker-compose.yml`

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#380]
When `fd2-up.bash` is run it uses the `docker-compose.yml` file to start the containers.  That script is now outputting the message:
``` 
WARN[0000] /Users/braught/code/FarmData2/FarmData2/docker/docker-compose.yml: 
the attribute `version` is obsolete, it will be ignored, 
please remove it to avoid potential confusion 
```

This should be investigated and resolved.  
- Is this dependent on the version of Docker/ Docker Desktop being used?  
- What happens to older versions if we remove the `version` attribute?
- Do we need to update the install docs to indicate a newer version of Docker Desktop as required?

**Comment by WarpWing** [comment]
> When `fd2-up.bash` is run it uses the `docker-compose.yml` file to start the containers. That script is now outputting the message:
> 
> ```
> WARN[0000] /Users/braught/code/FarmData2/FarmData2/docker/docker-compose.yml: 
> the attribute `version` is obsolete, it will be ignored, 
> please remove it to avoid potential confusion 
> ```
> 
> This should be investigated and resolved.
> 
>     * Is this dependent on the version of Docker/ Docker Desktop being used?
> 
>     * What happens to older versions if we remove the `version` attribute?
> 
>     * Do we need to update the install docs to indicate a newer version of Docker Desktop as required?

As I understand, it shouldn't be a problem as Docker Compose v2 (I want to say around 20.10, don't quote me) and any 3.x docker compose version (like 3.8) doesn't require the `version` key.  Unless we want to use a pre-xx build, we can safely remove it.  As for the documentation, I believe any version in Docker Compose v2 and 3.x file format version would be sufficient to notate. It feels weird (mostly because docker-compose always had a version like 3.8 or 3.9 file format wise) but if we really need to remove it, that's my insight.

**Comment by WarpWing** [comment]
@braughtg relevant information
https://github.com/compose-spec/compose-spec/blob/main/spec.md#compose-file
https://github.com/docker/compose/issues/11628 
https://forums.docker.com/t/do-you-need-to-put-the-version-at-the-top-of-docker-compose-yml-file/135863
https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

**Comment by braughtg** [comment]
Based on the above the resolution of this issue is to:
1. Remove the `version: '3'` line from `docker-compose.yml`
2. Rename `docker-comopose.yml` to  be `compose.yaml`
3. Confirm that `fd2-up.bash` and `fd2-down.bash` continue to work as expected

**Comment by WarpWing** [comment]
> Based on the above the resolution of this issue is to:
> 
>     1. Remove the `version: '3'` line from `docker-compose.yml`
> 
>     2. Rename `docker-compose.yml` to  be `compose.yaml`
> 
>     3. Confirm that `fd2-up.bash` and `fd2-down.bash` continue to work as expected

Alrighty. After I make the update for the squashMergeScript and make the test cases, if you (or I can of course) put it on the project board, I can get to it, doesn't seem like a big task.
