### ISSUE TITLE
Refactor PicklistBase Component: Improve `picked` Array to Store Selected Rows by `uuid` or Index

### ISSUE THREAD

**Issue by Shahir-47** [FarmData2/FarmData2#383]
## Issue Description

We need to remodel the `PicklistBase` component so that the `picked` array only stores the selected rows (as `uuid`s or original indices), rather than using `1`s and `0`s to track selections. This will resolve an issue where sorting causes a mismatch between the displayed rows and the actual data.

### Why This is an Issue
Currently, when sorting is applied via the column headers, the `sortedRows` (an internal copy of the `rows` array) is re-ordered to reflect the sort order. However, the `picked` array, which tracks selected items with `1`s and `0`s, is also shuffled to align with the sorted `sortedRows` data. 

Because the `rows` array (the original unsorted data) remains unchanged, there is a discrepancy between the sorted `picked` array and the original data. This means that when a user selects a row in the sorted list, it may map to the wrong item in the unsorted `rows` array. 

This problem becomes more significant when the `PicklistBase` component is used by other pages (such as Transplanting), as these pages expect the `picked` array to match the original order of the `rows` data. Without this match, selections may reference incorrect data entries, leading to errors in submission or other processes.

### Why It Needs Refactoring
This issue highlights the need for `picked` to store references to the selected rows using either the `uuid` of each item or the original index in the `rows` array. By doing so, we avoid the confusion caused by reordering the internal `sortedRows` array. This refactor will ensure that sorting behavior does not interfere with the correctness of selections and that developers using the `PicklistBase` component can work with it in a predictable manner without needing to manipulate or access its internal state (e.g., `sortedRows`). 

The refactor will:
1. Change `picked` to only store selected rows, identified by their `uuid` or original index in the `rows` array.
2. Ensure sorting via the `handleSort` method continues to work, while preserving the correct relationship between selected items and the original data.
3. Prevent users from needing to understand the internal structure of `sortedRows`, allowing them to use the `PicklistBase` component without worrying about the internal sorting logic.

#### Component Updates
- **PicklistBase.vue**: Refactor the `picked` array to only store selected rows (either by original index or `uuid`).

#### Component Tests Updates
- `PicklistBase.behavior.comp.cy.js`
- `PicklistBase.content.comp.cy.js`
- `PicklistBase.event.comp.cy.js`
- `PicklistBase.behavior.styling.cy.js`

#### TransplantingPicklist Component & Tests Updates
Since `TransplantingPicklist` uses `PicklistBase`, the following files will also need to be updated:
- **TransplantingPicklist.vue** (or equivalent component)
- `TransplantingPicklist.styling.comp.cy.js`
- `TransplantingPicklist.events.comp.cy.js`
- `TransplantingPicklist.content.comp.cy.js`
- `TransplantingPicklist.behavior.comp.cy.js`

#### Transplanting Page and Tests Updates
The `Transplanting` page uses the `TransplantingPicklist` component, which in turn uses `PicklistBase`. The following files will need to be updated:
- **Transplanting.vue** (or equivalent component)
- `transplanting.crop.e2e.cy.js`
- `transplanting.submission.e2e.cy.js`
- `transplanting.submitReset.e2e.cy.js`

#### Example Pages Updates
The following example pages need to be updated to reflect the changes in `PicklistBase`:
- **modules/farm_fd2_examples/src/entrypoints/picklist_base/App.vue**
- **modules/farm_fd2_examples/src/entrypoints/transplanting_picklist/App.vue**

#### End-to-End Test Updates
The end-to-end tests related to transplanting also need to be updated:
- **modules/farm_fd2/src/entrypoints/transplanting/transplanting.*.e2e.cy.js**

#### Library File Updates
- **lib.js**: Relevant changes need to be applied to support the `PicklistBase` updates as used in Transplanting.

### Relation to Issue #372
This restructuring of the `PicklistBase` component will also help address the requirements of [#372](https://github.com/YOUR_REPO_NAME/issues/372) — *Transplanting: manage selection by crop x bed combinations*. By refactoring the `PicklistBase` component to handle individual plant x bed combinations correctly, we ensure that selections are accurately tracked and mapped, allowing for proper submission events as described in the original issue.

## Summary of Changes

This refactor will:
- Ensure the `picked` array only tracks selected rows by `uuid` or original index.
- Resolve issues caused by sorting by ensuring selections always map to the correct data in the `rows` array.
- Ensure developers can use `PicklistBase.vue` without needing to understand or manipulate its internal `sortedRows` structure.

**Comment by Shahir-47** [comment]
For the `PicklistBase` component refactor, I propose the following approach:

- The local data variable `pickedRows` will remain an array of `0`s and `1`s to keep track of selection states.
- The prop `picked` will be a map that stores only the checked/picked elements.

The reason for keeping `pickedRows` as an array is that the `BFormSelect` component requires a default value. Binding it directly to an empty map would cause errors since there are no default values available at initialization.

It's crucial for `BFormSelect` to have default values because otherwise, it throws an error when the `v-on:change` event compares the new value with the previous value. If no default values are provided, the previous value is `undefined` or `null`, and this leads to a mismatch when comparing it to the newly selected value, causing an error.

This approach should ensure smooth selection handling and avoid errors due to undefined previous values in `BFormSelect`.

**Comment by braughtg** [comment]
> For the `PicklistBase` component refactor, I propose the following approach:
> 
>     * The local data variable `pickedRows` will remain an array of `0`s and `1`s to keep track of selection states.
> 
>     * The prop `picked` will be a map that stores only the checked/picked elements.
> 
> 
> The reason for keeping `pickedRows` as an array is that the `BFormSelect` component requires a default value. Binding it directly to an empty map would cause errors since there are no default values available at initialization.
> 
> It's crucial for `BFormSelect` to have default values because otherwise, it throws an error when the `v-on:change` event compares the new value with the previous value. If no default values are provided, the previous value is `undefined` or `null`, and this leads to a mismatch when comparing it to the newly selected value, causing an error.
> 
> This approach should ensure smooth selection handling and avoid errors due to undefined previous values in `BFormSelect`.

In addition to your two bullet points, the payload of the emitted event should also be a map. 

That will ensure that the abstraction is complete.  From outside of the component, everything will look like it is operating on a map rather than an array.  Internally, it will use the array for the reasons that you mention.
