### ISSUE TITLE
Add `updatePlantAsset` function to `farmosUtil.js` and implement tests

### ISSUE THREAD

**Issue by Shahir-47** [FarmData2/FarmData2#389]
### Summary
We need to add an `updatePlantAsset` function to `farmosUtil.js` to support updating individual attributes of plant assets, particularly for modifying attributes like `beds` during various operations.

### Details
The `updatePlantAsset` function will provide a flexible way to update specific attributes of a plant asset. It will take the `uuid` of the plant asset, the attribute name, and the new attribute value as arguments. This will allow for easy modification of attributes such as the `beds` array, which is necessary for handling soil disturbance and termination events.

The function should:
- Fetch the existing plant asset.
- Update only the specified attribute while preserving the rest of the data.
- Save the updated plant asset back to the system.

This approach will help ensure that future use cases involving dynamic modifications to plant assets are well supported.

### Tasks
1. Create an `updatePlantAsset` function in `farmosUtil.js` that takes `(uuid, attributeName, attributeValue)` as parameters.
2. Implement tests to verify the functionality of `updatePlantAsset`, ensuring that the function updates attributes correctly while keeping other data intact.
3. Ensure that the function handles errors gracefully, such as when a plant asset does not exist.

### References
This issue is intended to support #388, which requires modifying plant assets during soil disturbance operations.

**Comment by braughtg** [comment]
>     1. Create an `updatePlantAsset` function in `farmosUtil.js` that takes `(uuid, attributeName, attributeValue)` as parameters.
> 

If we want to update multiple attributes this could get tedious.  What if the function accepts an object with `attrubuteName:attributeValue` pairs?  Then we could update all of the attributes included in that object.  

For example passing the following would update both `attr1` and `attr2`:
```
{
   attr1: value1,
   attr2: value2,
}
```

**Comment by Shahir-47** [comment]
Hi @braughtg,

I encountered a scenario while working on `updatePlantAsset()`. Specifically, if the user attempts to update an attribute that does not currently exist (like `beds` in some cases), should the function create that attribute?

For instance, if the `beds` attribute is missing from the `attributes` object and the user wants to update it, should we automatically add it to the plant asset?

Moreover, I noticed that the `createPlantAsset()` function does not provide an option to assign `beds` to the newly created plant asset, nor does any other function in `farmosUtil.js`. This makes testing challenging since the `beds` attribute isn't initially set unless we explicitly create it during the update.

Let me know your thoughts on this when you get a chance.

Thanks!

**Comment by braughtg** [comment]
> For instance, if the `beds` attribute is missing from the `attributes` object and the user wants to update it, should we automatically add it to the plant asset?

Adding the attribute if it does not exist seems like the appropriate action here.  Be sure that that functionality is clearly documented in the function's JSDoc comments.

**Comment by braughtg** [comment]
It appears that this function may not be required at this time.  The motivating use case was to update the locations of a plant asset.  The way that should be done is via a movement log.  

This is being left open for the moment just to ensure that the underlying task (~#338~ #388) can be resolved with out it.  If ~#338~ #388 can be resolved without this function, then this issue should be closed.

**Comment by Shahir-47** [comment]
> This is being left open for the moment just to ensure that the underlying task ([#338](https://github.com/FarmData2/FarmData2/pull/338)) can be resolved with out it. If [#338](https://github.com/FarmData2/FarmData2/pull/338) can be resolved without this function, then this issue should be closed.

Just a quick note: the correct issue number is #388, not #338.

**Comment by braughtg** [comment]
@Shahir-47 Should we close this issue at this point?

**Comment by Shahir-47** [comment]
> @Shahir-47 Should we close this issue at this point?

Yes.
