### ISSUE TITLE
Change code docs index page to use markdown table

### ISSUE THREAD

**Issue by braughtg** [FarmData2/FarmData2#39]
The main index page created by the `bin/makeDocs.bash` script currently uses bullets to list each of the components and libraries that are documented.  The presentation would be better if it were a table with two columns for "Name" and "Description".  The content would be the same as it currently is, just laid out in a table instead of a bulleted list.

The docs are generated using: `npm run docs:gen`
Then they are viewed using `npm run docs:view`

**Comment by Shahir-47** [comment]
After resolving the SC2129 – ShellCheck error, I got the following error when committing, which is the same one I got for #261:

![image](https://github.com/FarmData2/FarmData2/assets/98346408/56660e82-2d7f-44ae-b80d-e67a4497041a)
