### ISSUE TITLE
Create GitPod to run FD2 Dev Environment

### ISSUE THREAD

**Issue by FutzMonitor** [FarmData2/FarmData2#77]
## Current Design 
Currently the dev environment uses Docker which has some cross-platform issues that need to be addressed to work on both Windows WSL2 and Linux. 

## Desired Design
It would be ideal if we could figure out how to utilize [Gitpod](https://www.gitpod.io/) to build the development environment instead of Docker so that it's entirely platform independent and the FarmData2 team can stop worrying about the OS specifics when building the development environment. 

This also removes additional obstacles including installing WSL and Docker Desktop.  A VNC client would be the only dependency (unless you use noVNC and then there are none other than a browser).

**Comment by braughtg** [comment]
Ideally, I think there should be a variety of options available to developers:
- Gitpod: super easy and quick to get going but will be limited in some ways (cost/hour, persistence of database?)
  - via noVNC
  - via a VNC client
- Dockerized `fd2_dev` container: uniform development environment with some setup challenges particularly on WSL.
- Native OS: easier with npm dependencies, but still will require some developer maturity to setup and have fully working.

**Comment by braughtg** [comment]
I have a spike repo that shows how to run a debian Linux container (similar to fd2-dev) in GitPod, which can then be connected to via noVnc or a full VNC client.

The repo is here: https://github.com/braughtg/gitpodVNC

The approach for FD2 Dev Environment should be something like:
- Put an adapted `.gitpod.yml` file in the FarmData2 repo
- Don't do anything in the tasks (at least initially)
- run `fd2-up.bash` in the GitPod Terminal.
- Connect via noVnc or VNC.

Eventually, it may make sense to have a custom image that just launches the FarmData dev environment that is started in GitPod.  Then there would be nothing to do but, open in GitPod and click the link to get into noVNC (or do the setup to get the VNC connection).

**Comment by braughtg** [comment]
When this is running it will also be important to run all of the tests and adjust timeouts as/if necessary so that tests do not fail due to timeouts if the gitpod machine is slower than the one I've been developing on.

**Comment by braughtg** [comment]
> I have a spike repo that shows how to run a debian Linux container (similar to fd2-dev) in GitPod, which can then be connected to via noVnc or a full VNC client.

There is a production version of this being used in: https://gitlab.com/hfossedu/kits/kitclient-linux-gitpod

**Comment by braughtg** [comment]
# Design idea:
- Start the fd2-dev container (via docker or via GitPod).
  - Mount volumes as they are now except for the local repo.
- Connect to the fd2-dev container via VNC or noVNC.
- Manually clone the FD2 origin repo into the container.
  - this is as opposed to cloning to the host machine and mounting it from there as is done currently.
    - This eliminates the permissions issues with Linux/WSL.
- Then use docker-in-docker to start the db and farmos containers from inside the fd2-dev container.
  - Can still mount the appropriate directories and volumes into those containers.

This should have the advantage of allowing devs to not use the fd2-dev container if they want to do their own setup.
  - Just ensure all dependencies are installed and clone to the local machine.
  - Then start the db and farmos containers on the local machine
  - There will be some issues with scripts that are expecting to run in fd2-dev.
     - they may be able to be adapted to run outside of fd2-dev if all of their dependencies are installed.

 # Implementation:
- Use profiles in the docker-compose file to:
  - Start just fd2-dev
  - Start just db and farmos

- Add files like those in https://gitlab.com/hfossedu/kits/kitclient-linux-gitpod to the FD2 repo
  - .gitpod.dockerfile (modify name and location of script)
  - .gitpotd.yml (identical)
  - startup.bash (modify name, location and adapt script)
